version: '3'

services:
  flask:
    build: .
    volumes:
      - .:/usr/src/app
      - /home/chris/pdfs/:/home/chris/pdfs # Get access to PDFs from server
    ports:
      - "127.0.0.1:5000:5000" # Set host to be 127.0.0.0 instad of 0.0.0.0. So that it can not be accessed directly remotly with: "IP_to_server:5000".
    command: gunicorn -w 1 -b :5000 run:app # Remove --reload before deployment to production. Or add if testing locally.

  nginx:
    build: ./proxy # Builds the Dockerfile in the proxy folder.
    volumes:
      - ./app/static/:/etc/nginx/static # Since the app/static folder is one folder up, COPY in the Dockerfile does not work. 
                                        #Read more about the difference between volumemounting and copying. 
    ports:
      - "80:80" 
    depends_on:
      - flask
